- name: general tasks
  hosts: all
  become: true
  roles:
   - { role: general, tags: ["always"] }



###
# IDEs
###

- name: plain eclipse installation
  hosts: all
  become: true
  roles:
   - { role: eclipse, tags: ["eclipse"] }

- name: Atom Editor
  hosts: all
  become: true
  roles:
   - { role: atom, tags: ["atom"] }



###
# Nodejs
###

- name: nodejs server
  hosts: all
  become: true
  roles:
   - { role: nodejs, tags: ["nodejs"] }

- name: nodejs development dependencies
  hosts: all
  become: true
  roles:
   - { role: nodejs-dev, tags: ["nodejs-dev"] }



# Wowza
- name: wowza streaming server
  hosts: all
  become: true
  roles:
   - { role: wowza, tags: ["wowza"] }
- name: wowza development with preconfigured eclipse
  hosts: all
  become: true
  roles:
   - { role: wowza-dev, tags: ["wowza-dev"] }
